# Branch Protection Configuration
# This file documents the recommended branch protection settings
# These should be configured in GitHub repository settings

main:
  protection:
    required_status_checks:
      strict: true
      contexts:
        - "Frontend Quality Checks"
        - "Backend Quality Checks"
        - "Integration Tests"
        - "Quality Gate & Metrics"
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      restrict_pushes: true
    restrictions:
      users: []
      teams: []
    allow_force_pushes: false
    allow_deletions: false

develop:
  protection:
    required_status_checks:
      strict: true
      contexts:
        - "Frontend Quality Checks"
        - "Backend Quality Checks"
        - "Integration Tests"
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
    allow_force_pushes: false
    allow_deletions: false