# Quality Gates Configuration
# This file defines the quality thresholds and gates for CI/CD

quality_gates:
  # Coverage thresholds
  coverage:
    frontend:
      minimum: 80
      target: 85
    backend:
      minimum: 80
      target: 90
    overall:
      minimum: 80
      target: 85

  # Code quality thresholds
  code_quality:
    eslint_errors: 0
    typescript_errors: 0
    flake8_errors: 0
    mypy_errors: 0
    security_high_issues: 0
    security_medium_issues: 5  # Allow some medium issues but track them

  # Performance thresholds
  performance:
    build_time_max: 300  # seconds
    test_time_max: 120   # seconds
    bundle_size_max: 2048  # KB

  # Complexity thresholds
  complexity:
    cyclomatic_max: 10
    maintainability_min: 70

# Quality gate enforcement levels
enforcement:
  # Block merge if these gates fail
  blocking:
    - eslint_errors
    - typescript_errors
    - flake8_errors
    - mypy_errors
    - security_high_issues
    - coverage_minimum
    - test_failures

  # Warn but allow merge if these gates fail
  warning:
    - security_medium_issues
    - complexity_violations
    - performance_degradation

# Notification settings
notifications:
  slack:
    enabled: false
    webhook_url: ""
    channels:
      - "#dev-quality"
  
  email:
    enabled: false
    recipients:
      - "dev-team@company.com"

# Quality metrics collection
metrics:
  enabled: true
  retention_days: 90
  export_formats:
    - json
    - csv
  
  tracked_metrics:
    - coverage_percentage
    - error_count
    - warning_count
    - test_count
    - build_time
    - complexity_score