# Hadolint configuration for Ubuntu compatibility
# https://github.com/hadolint/hadolint

# Ignore specific rules that may not apply to our use case
ignored:
  # DL3008: Pin versions in apt get install (we handle this in requirements)
  # DL3009: Delete the apt-get lists after installing something (handled by multi-stage builds)
  # DL3015: Avoid additional packages by specifying --no-install-recommends (context dependent)
  
# Trusted registries for base images (Ubuntu-focused)
trustedRegistries:
  - docker.io
  - registry-1.docker.io
  - ubuntu
  - python
  - node
  - nginx
  - postgres
  - redis

# Override specific rules for Ubuntu compatibility
override:
  error:
    # Critical Ubuntu compatibility issues
    - DL3002  # Last USER should not be root (security)
    - DL3003  # Use WORKDIR for switching to a directory (path handling)
    - DL3020  # Use COPY instead of ADD for files and folders (security)
    - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT (shell compatibility)
    - DL4006  # Set the SHELL option -o pipefail before RUN with a pipe (Ubuntu bash)
    
  warning:
    # Important but not critical
    - DL3007  # Using latest is prone to errors (version pinning)
    - DL3008  # Pin versions in apt get install
    - DL3009  # Delete the apt-get lists after installing something
    - DL3015  # Avoid additional packages by specifying --no-install-recommends
    - DL3018  # Pin versions in apk add
    - DL3019  # Use the --no-cache switch to avoid the need to use --update and remove /var/cache/apk/*
    - DL3027  # Do not use apt as it is meant to be an end-user tool
    
  info:
    # Style and best practices
    - DL3006  # Always tag the version of an image explicitly
    - DL3010  # Use ADD for extracting archives into an image
    - DL3013  # Pin versions in pip
    - DL3016  # Pin versions in npm
    - DL3028  # Pin versions in gem install

# Specific rules for Ubuntu base images
format: json

# Failure threshold
failure-threshold: error

# Inline ignore patterns
inline-ignore:
  # Allow inline ignoring with comments like: # hadolint ignore=DL3008
  - "# hadolint ignore="
  - "# hadolint disable="

# Strict mode for production builds
strict: false

# Custom rules for Ubuntu-specific patterns
custom-rules:
  # Ensure Ubuntu packages are properly updated
  - name: "ubuntu-apt-update"
    description: "Ensure apt-get update is run before apt-get install"
    pattern: "RUN.*apt-get install"
    message: "Run 'apt-get update' before 'apt-get install'"
    
  # Check for proper cleanup
  - name: "ubuntu-cleanup"
    description: "Clean up apt cache after installation"
    pattern: "RUN.*apt-get install.*&&.*rm -rf /var/lib/apt/lists/*"
    message: "Clean up apt cache with 'rm -rf /var/lib/apt/lists/*'"
    
  # Ensure non-root user creation
  - name: "ubuntu-user-creation"
    description: "Create non-root user for security"
    pattern: "RUN.*useradd|RUN.*adduser"
    message: "Create non-root user for better security"

# File patterns to analyze
include:
  - "Dockerfile*"
  - "*.dockerfile"
  - "**/Dockerfile*"

# File patterns to exclude
exclude:
  - "node_modules/**"
  - ".git/**"
  - "venv/**"
  - ".venv/**"
  - "__pycache__/**"