# Simplified AI Services Configuration
# ChromaDB and Ollama with minimal resource requirements

services:
  # Simplified ChromaDB
  chromadb-simple:
    image: chromadb/chroma:0.4.18
    container_name: ai-scholar-chromadb-simple
    restart: unless-stopped
    ports:
      - "8081:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False
      - ALLOW_RESET=True
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    volumes:
      - ./data/chroma:/chroma/chroma
    networks:
      - ai-scholar-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/heartbeat || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Simplified Ollama
  ollama-simple:
    image: ollama/ollama:latest
    container_name: ai-scholar-ollama-simple
    restart: unless-stopped
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - ai-scholar-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

networks:
  ai-scholar-network:
    external: true

volumes:
  chroma_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/chroma
  ollama_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/ollama