# Continuous Monitoring and Alerting System Configuration

monitoring:
  # Check interval in minutes
  check_interval_minutes: 60
  
  # Data retention period in days
  retention_days: 30
  
  # Enable different alert channels
  enable_email_alerts: false
  enable_slack_alerts: false
  enable_webhook_alerts: false
  
  # Enable monitoring dashboard
  enable_dashboard: true
  dashboard_port: 8080

# Quality gate thresholds
quality_gates:
  # Maximum number of critical issues allowed
  max_critical_issues: 0
  
  # Maximum number of high severity issues allowed
  max_high_issues: 5
  
  # Maximum total number of issues allowed
  max_total_issues: 50
  
  # Minimum test coverage percentage required
  min_test_coverage: 80.0
  
  # Maximum Ubuntu compatibility issues allowed
  max_ubuntu_compatibility_issues: 2
  
  # Build success requirement
  require_build_success: true
  
  # Deployment validation requirement
  require_deployment_success: true

# Regression detection settings
regression_detection:
  # Enable regression detection
  enabled: true
  
  # Historical data window for comparison (days)
  comparison_window_days: 7
  
  # Thresholds for regression alerts
  thresholds:
    # Percentage increase in total issues to trigger alert
    total_issues_increase_percent: 20
    
    # Absolute increase in critical issues to trigger alert
    critical_issues_increase: 1
    
    # Percentage decrease in test coverage to trigger alert
    coverage_decrease_percent: 5
    
    # Any increase in Ubuntu compatibility issues triggers alert
    ubuntu_issues_increase: 1

# Alert configuration
alerts:
  email:
    smtp_server: "localhost"
    smtp_port: 587
    use_tls: true
    username: ""
    password: ""
    recipients: []
    
  slack:
    webhook_url: ""
    channel: "#code-quality"
    username: "Code Quality Monitor"
    icon_emoji: ":warning:"
    
  webhook:
    url: ""
    headers:
      Content-Type: "application/json"
    timeout_seconds: 30

# Maintenance automation settings
maintenance:
  # Enable automated fixes for auto-fixable issues
  auto_fix_enabled: true
  
  # Enable automatic dependency updates
  auto_update_dependencies: false
  
  # Enable automatic code formatting
  auto_format_code: true
  
  # Create backup before applying fixes
  backup_before_fixes: true
  
  # Maximum number of auto-fixes to apply per cycle
  max_auto_fixes_per_cycle: 10
  
  # Backup retention period in days
  backup_retention_days: 7

# CI/CD integration settings
cicd_integration:
  # Enable quality gate enforcement in CI/CD
  enable_quality_gates: true
  
  # Fail CI/CD pipeline on quality gate failures
  fail_on_gate_failure: true
  
  # Generate quality reports for CI/CD
  generate_reports: true
  
  # Report formats to generate
  report_formats:
    - json
    - html
    - junit
  
  # Upload reports to external systems
  upload_reports: false
  
  # External report destinations
  report_destinations: []

# Ubuntu compatibility monitoring
ubuntu_monitoring:
  # Enable Ubuntu-specific monitoring
  enabled: true
  
  # Ubuntu version to target
  target_version: "24.04.2"
  
  # Monitor Docker compatibility
  monitor_docker: true
  
  # Monitor package dependencies
  monitor_packages: true
  
  # Monitor shell script compatibility
  monitor_scripts: true
  
  # Alert on Ubuntu-specific issues
  alert_on_ubuntu_issues: true

# Performance monitoring
performance_monitoring:
  # Enable performance regression detection
  enabled: true
  
  # Performance thresholds
  thresholds:
    # Maximum build time in seconds
    max_build_time: 600
    
    # Maximum test execution time in seconds
    max_test_time: 300
    
    # Maximum analysis time in seconds
    max_analysis_time: 1800
    
    # Memory usage threshold in MB
    max_memory_usage: 2048

# Dashboard configuration
dashboard:
  # Enable web dashboard
  enabled: true
  
  # Dashboard port
  port: 8080
  
  # Dashboard host (0.0.0.0 for all interfaces)
  host: "localhost"
  
  # Enable authentication
  enable_auth: false
  
  # Dashboard refresh interval in seconds
  refresh_interval: 30
  
  # Charts to display
  charts:
    - quality_trends
    - issue_distribution
    - gate_status
    - ubuntu_compatibility
    - test_coverage
    - build_status

# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  
  # Log file path
  file: "monitoring.log"
  
  # Maximum log file size in MB
  max_file_size: 10
  
  # Number of backup log files to keep
  backup_count: 5
  
  # Log format
  format: "%(asctime)s - %(levelname)s - %(message)s"

# Database configuration
database:
  # Database type (sqlite, postgresql, mysql)
  type: "sqlite"
  
  # Database file path (for SQLite)
  path: "monitoring.db"
  
  # Connection settings (for other databases)
  host: "localhost"
  port: 5432
  username: ""
  password: ""
  database: "monitoring"
  
  # Connection pool settings
  pool_size: 5
  max_overflow: 10