#!/usr/bin/env python3
"""
Setup script for Category 6: Proactive & Ubiquitous Integration
Helps configure OAuth credentials and environment variables
"""

import os
import sys
import json
from pathlib import Path

def print_header(title):
    """Print formatted header"""
    print(f"\n{'='*60}")
    print(f"{title}")
    print(f"{'='*60}")

def print_step(step_num, title):
    """Print step header"""
    print(f"\n🔧 Step {step_num}: {title}")
    print("-" * 40)

def get_user_input(prompt, default=None, required=True):
    """Get user input with optional default"""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "
    
    while True:
        value = input(full_prompt).strip()
        
        if value:
            return value
        elif default:
            return default
        elif not required:
            return ""
        else:
            print("This field is required. Please enter a value.")

def create_env_file():
    """Create or update .env file with OAuth credentials"""
    print_step(1, "OAuth Credentials Configuration")
    
    print("To enable automated knowledge syncing, you need to configure OAuth credentials")
    print("for the platforms you want to connect. You can skip any platform you don't need.")
    print("\nFor setup instructions, visit:")
    print("• Google Drive: https://developers.google.com/drive/api/quickstart/python")
    print("• Notion: https://developers.notion.com/docs/authorization")
    print("• GitHub: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps")
    print("• Dropbox: https://developers.dropbox.com/oauth-guide")
    
    # Read existing .env file if it exists
    env_file = Path('.env')
    existing_vars = {}
    
    if env_file.exists():
        print(f"\n📁 Found existing .env file")
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key] = value
    
    # OAuth credentials to configure
    oauth_configs = {
        'Google Drive': {
            'client_id': 'GOOGLE_CLIENT_ID',
            'client_secret': 'GOOGLE_CLIENT_SECRET'
        },
        'Notion': {
            'client_id': 'NOTION_CLIENT_ID',
            'client_secret': 'NOTION_CLIENT_SECRET'
        },
        'GitHub': {
            'client_id': 'GITHUB_CLIENT_ID',
            'client_secret': 'GITHUB_CLIENT_SECRET'
        },
        'Dropbox': {
            'client_id': 'DROPBOX_CLIENT_ID',
            'client_secret': 'DROPBOX_CLIENT_SECRET'
        }
    }
    
    new_vars = existing_vars.copy()
    
    for platform, vars_config in oauth_configs.items():
        print(f"\n🔗 {platform} Configuration")
        
        configure = get_user_input(
            f"Do you want to configure {platform}? (y/n)", 
            "n", 
            required=False
        ).lower() == 'y'
        
        if configure:
            for var_name, env_var in vars_config.items():
                current_value = existing_vars.get(env_var, '')
                if current_value:
                    print(f"Current {var_name}: {current_value[:10]}...")
                
                new_value = get_user_input(
                    f"Enter {platform} {var_name.replace('_', ' ').title()}",
                    current_value if current_value else None,
                    required=False
                )
                
                if new_value:
                    new_vars[env_var] = new_value
    
    # Celery configuration
    print(f"\n⚙️ Celery Configuration")
    
    celery_vars = {
        'CELERY_BROKER_URL': 'redis://localhost:6379/0',
        'CELERY_RESULT_BACKEND': 'redis://localhost:6379/0'
    }
    
    for var_name, default_value in celery_vars.items():
        current_value = existing_vars.get(var_name, default_value)
        new_value = get_user_input(
            f"Enter {var_name}",
            current_value,
            required=False
        )
        
        if new_value:
            new_vars[var_name] = new_value
    
    # Write updated .env file
    with open(env_file, 'w') as f:
        f.write("# AI Scholar Environment Configuration\n")
        f.write("# Generated by setup_proactive_integration.py\n\n")
        
        f.write("# Database Configuration\n")
        if 'DATABASE_URL' in new_vars:
            f.write(f"DATABASE_URL={new_vars['DATABASE_URL']}\n")
        f.write("\n")
        
        f.write("# OAuth Credentials for Data Source Integration\n")
        for platform, vars_config in oauth_configs.items():
            f.write(f"# {platform}\n")
            for var_name, env_var in vars_config.items():
                if env_var in new_vars:
                    f.write(f"{env_var}={new_vars[env_var]}\n")
            f.write("\n")
        
        f.write("# Celery Configuration\n")
        for var_name in celery_vars:
            if var_name in new_vars:
                f.write(f"{var_name}={new_vars[var_name]}\n")
        f.write("\n")
        
        # Add any other existing variables
        other_vars = {k: v for k, v in new_vars.items() 
                     if k not in [env_var for config in oauth_configs.values() for env_var in config.values()] 
                     and k not in celery_vars 
                     and k != 'DATABASE_URL'}
        
        if other_vars:
            f.write("# Other Configuration\n")
            for var_name, value in other_vars.items():
                f.write(f"{var_name}={value}\n")
    
    print(f"\n✅ Environment configuration saved to {env_file}")

def setup_browser_extension():
    """Setup browser extension configuration"""
    print_step(2, "Browser Extension Setup")
    
    print("The browser extension is located in the 'browser-extension/' directory.")
    print("To install and use the extension:")
    
    print("\n📋 Installation Steps:")
    print("1. Open Chrome and go to chrome://extensions/")
    print("2. Enable 'Developer mode' in the top right")
    print("3. Click 'Load unpacked' and select the 'browser-extension' folder")
    print("4. The AI Scholar extension should now appear in your extensions")
    
    print("\n🔧 Configuration:")
    print("1. Click the AI Scholar extension icon in your browser")
    print("2. Enter your AI Scholar API key (create one in the dashboard)")
    print("3. Configure your preferred settings")
    print("4. Start using AI assistance on any webpage!")
    
    print("\n⌨️ Usage:")
    print("• Select text on any webpage")
    print("• Click the floating AI Scholar button or use keyboard shortcuts:")
    print("  - Ctrl+Shift+E: Explain selected text")
    print("  - Ctrl+Shift+S: Summarize selected text")
    print("  - Ctrl+Shift+R: Rewrite selected text")
    print("• View results in the popup modal or sidebar")

def setup_celery_workers():
    """Setup Celery workers for background tasks"""
    print_step(3, "Celery Workers Setup")
    
    print("Celery workers handle background tasks for automated knowledge syncing.")
    print("You need to start Celery workers to enable automatic document processing.")
    
    print("\n📋 Setup Steps:")
    print("1. Install Redis (if not already installed):")
    print("   • Ubuntu/Debian: sudo apt-get install redis-server")
    print("   • macOS: brew install redis")
    print("   • Windows: Download from https://redis.io/download")
    
    print("\n2. Start Redis server:")
    print("   redis-server")
    
    print("\n3. Start Celery worker (in a separate terminal):")
    print("   celery -A tasks.sync_tasks worker --loglevel=info")
    
    print("\n4. Start Celery Beat scheduler (in another terminal):")
    print("   celery -A tasks.sync_tasks beat --loglevel=info")
    
    print("\n5. Optional: Start Celery Flower for monitoring:")
    print("   celery -A tasks.sync_tasks flower")
    print("   Then visit http://localhost:5555 for the monitoring dashboard")

def create_startup_scripts():
    """Create startup scripts for easy development"""
    print_step(4, "Startup Scripts Creation")
    
    # Create start_celery.sh script
    celery_script = """#!/bin/bash
# Start Celery workers and beat scheduler for AI Scholar

echo "Starting AI Scholar Celery services..."

# Check if Redis is running
if ! pgrep -x "redis-server" > /dev/null; then
    echo "Starting Redis server..."
    redis-server --daemonize yes
fi

# Start Celery worker in background
echo "Starting Celery worker..."
celery -A tasks.sync_tasks worker --loglevel=info --detach

# Start Celery beat scheduler in background
echo "Starting Celery beat scheduler..."
celery -A tasks.sync_tasks beat --loglevel=info --detach

# Optional: Start Flower monitoring
if command -v flower &> /dev/null; then
    echo "Starting Celery Flower monitoring..."
    celery -A tasks.sync_tasks flower --detach
    echo "Flower monitoring available at: http://localhost:5555"
fi

echo "✅ Celery services started successfully!"
echo "To stop services, run: pkill -f celery"
"""
    
    with open('start_celery.sh', 'w') as f:
        f.write(celery_script)
    
    os.chmod('start_celery.sh', 0o755)
    
    # Create stop_celery.sh script
    stop_script = """#!/bin/bash
# Stop Celery workers and beat scheduler

echo "Stopping AI Scholar Celery services..."

# Stop Celery processes
pkill -f "celery.*worker"
pkill -f "celery.*beat"
pkill -f "celery.*flower"

echo "✅ Celery services stopped!"
"""
    
    with open('stop_celery.sh', 'w') as f:
        f.write(stop_script)
    
    os.chmod('stop_celery.sh', 'w') 
    
    print("✅ Created startup scripts:")
    print("• start_celery.sh - Start all Celery services")
    print("• stop_celery.sh - Stop all Celery services")

def verify_installation():
    """Verify the installation and provide next steps"""
    print_step(5, "Installation Verification")
    
    print("Let's verify that everything is set up correctly:")
    
    # Check if required files exist
    required_files = [
        'services/browser_extension_service.py',
        'services/automated_sync_service.py',
        'tasks/sync_tasks.py',
        'tasks/rag_tasks.py',
        'browser-extension/manifest.json',
        '.env'
    ]
    
    missing_files = []
    for file_path in required_files:
        if not Path(file_path).exists():
            missing_files.append(file_path)
    
    if missing_files:
        print("❌ Missing required files:")
        for file_path in missing_files:
            print(f"   • {file_path}")
        print("\nPlease ensure all files are properly installed.")
    else:
        print("✅ All required files are present")
    
    # Check environment variables
    env_file = Path('.env')
    if env_file.exists():
        print("✅ Environment configuration file exists")
    else:
        print("❌ Environment configuration file missing")
    
    # Provide next steps
    print("\n🚀 Next Steps:")
    print("1. Start the AI Scholar backend server:")
    print("   python app_enterprise.py")
    
    print("\n2. Start Celery services (in separate terminals):")
    print("   ./start_celery.sh")
    print("   # or manually:")
    print("   celery -A tasks.sync_tasks worker --loglevel=info")
    print("   celery -A tasks.sync_tasks beat --loglevel=info")
    
    print("\n3. Load the browser extension:")
    print("   • Open Chrome extensions (chrome://extensions/)")
    print("   • Enable Developer mode")
    print("   • Load unpacked extension from 'browser-extension' folder")
    
    print("\n4. Test the integration:")
    print("   python test_proactive_integration.py")
    
    print("\n5. Create an API key in the AI Scholar dashboard")
    print("   • Log in to AI Scholar")
    print("   • Go to Settings > API Keys")
    print("   • Create a new key for browser extension")
    
    print("\n6. Configure the browser extension:")
    print("   • Click the extension icon")
    print("   • Enter your API key")
    print("   • Start using AI assistance on any webpage!")

def main():
    """Main setup function"""
    print_header("AI Scholar - Proactive Integration Setup")
    print("This script will help you configure Category 6 features:")
    print("• Browser Extension for ubiquitous AI assistance")
    print("• Automated Knowledge Syncing from external sources")
    print("• OAuth integration with Google Drive, Notion, GitHub, Dropbox")
    print("• Celery workers for background processing")
    
    try:
        create_env_file()
        setup_browser_extension()
        setup_celery_workers()
        create_startup_scripts()
        verify_installation()
        
        print_header("Setup Complete! 🎉")
        print("Your AI Scholar installation now includes:")
        print("✅ Browser extension for web-wide AI assistance")
        print("✅ Automated knowledge syncing capabilities")
        print("✅ OAuth integration for external data sources")
        print("✅ Background task processing with Celery")
        print("\nRefer to PROACTIVE_INTEGRATION_GUIDE.md for detailed usage instructions.")
        
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Setup failed: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()