version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_scholar
      - OLLAMA_URL=http://ollama:11434
      - CHROMA_PERSIST_DIR=/app/chroma_db
    volumes:
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
    depends_on:
      - db
      - ollama
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ai_scholar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull mistral &&
             ollama pull nomic-embed-text &&
             wait"

  frontend:
    build: ../
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: